### ISSUE TITLE
Doesn't work on Win32 platforms

### ISSUE THREAD

**Issue by jherico** [Sarcasm/run-clang-format#1]
I'm excited about this as a potential feature, but it doesn't work on my Windows desktop.  The use of `signal.signal(signal.SIGPIPE, signal.SIG_DFL)` crashes Python when I try to run.  I was able to get past this by commenting out that line.  However, the `readlines` method appears to produce a list of lines terminated by `\n` (this is somewhat confusing to me, since the file seems to have `\r\n` terminators) while the output of the clang-format process on windows produces output with `\r\n`.  The python difflib then marks everything as changed because of the line terminators.  

It would be preferable if the python code ensured that the two sets of lines had consistent line terminators, regardless of the output of `readlines` or `clang-format`

**Comment by Sarcasm** [comment]
Thanks for reporting the issue.
I committed some fixes, but did not test on Windows.
Can you give it a try?

**Comment by jherico** [comment]
Works, thanks.
