### ISSUE TITLE
Ambiguous error output when clang-format executable doesn't exist

### ISSUE THREAD

**Issue by username223** [Sarcasm/run-clang-format#13]
If you run the application with the optional `--clang-format-executable` and the executable doesn't exist you get the error message `run-clang-format.py: error: [Errno 2] No such file or directory`. While this is technically true, it does not truly represent what is wrong with the application.

If the application is run on a directory of files a message will appear for every file:
```bash
$ ls ./src
foo.cpp  foo2.cpp
$ python run-clang-format.py ./src -r --clang-format-executable clang-format-wrong
run-clang-format.py: error: [Errno 2] No such file or directory
run-clang-format.py: error: [Errno 2] No such file or directory
```
This could lead people to believe that there's something wrong with the file structure or source-file-finding function of the application instead of a missing package, or executable. This is especially annoying to debug when running on CI with limited resources.

Checking that the executable is present (with a `--version` call, or something) and having a relevant error message for this specific error would fix the issue.

___

Thank you for the excellent application. I'm surprised that this isn't done by the LLVM team, given how ubiquitous the use case is.

**Comment by Sarcasm** [comment]
FYI, in Python 3 the Python exception message is more helpful by default, as you get:

    run-clang-format.py: error: [Errno 2] No such file or directory: 'clang-format-wrong': 'clang-format-wrong'

Nevertheless, it's nice to have only one error at the start, than many errors.

I added a `clang-format --version` check at start, and tried to improve the various error messages.

Thank you for your bug report.
