### ISSUE TITLE
Failure when run with python 3.5

### ISSUE THREAD

**Issue by AMS21** [Sarcasm/run-clang-format#18]
Hello, I would love to use this tools as it does exactly what I want. But when running it on my CI builds I'm getting the following error:

> run-clang-format.py: error: OpenEast/include/Platform/Win32/Win32_Registry.hpp: TypeError: __init__() got an unexpected keyword argument 'encoding'
Traceback (most recent call last):
  File "/home/travis/build/AMS21/OpenEast/deps/run-clang-format/run-clang-format.py", line 118, in run_clang_format_diff_wrapper
    ret = run_clang_format_diff(args, file)
  File "/home/travis/build/AMS21/OpenEast/deps/run-clang-format/run-clang-format.py", line 163, in run_clang_format_diff
    **encoding_py3)
TypeError: __init__() got an unexpected keyword argument 'encoding'

[Full log](https://travis-ci.com/AMS21/OpenEast/jobs/272479328)

Not sure what to make of this and if it even has something todo with my [Win32_Registry.hpp](https://github.com/AMS21/OpenEast/blob/develop/OpenEast/include/Platform/Win32/Win32_Registry.hpp) file. Could also be possible that I miss configured something.
[Install script](https://github.com/AMS21/OpenEast/blob/develop/scripts/CI/linux.install_run_clang_format.sh)
[Run script](https://github.com/AMS21/OpenEast/blob/develop/scripts/CI/linux.style_check.clang_format.sh)

Hopefully you'll be able to help me.
Kind regard André

**Comment by Sarcasm** [comment]
Looks like you are using python3, but 'encoding' is support by `subprocess.Popen` only since Python 3.6:

- https://docs.python.org/3.6/library/subprocess.html#subprocess.Popen

Can you replace the code here:

https://github.com/Sarcasm/run-clang-format/blob/de6e8ca07d171a7f378d379ff252a00f2905e81d/run-clang-format.py#L153-L155

by:

```patch
     encoding_py3 = {}
-    if sys.version_info[0] >= 3:
+    if sys.version_info[:2] >= (3, 6):
         encoding_py3['encoding'] = 'utf-8'
```

And a little below:

https://github.com/Sarcasm/run-clang-format/blob/de6e8ca07d171a7f378d379ff252a00f2905e81d/run-clang-format.py#L172-L177

By:

```patch
-    if sys.version_info[0] < 3:
-        # make the pipes compatible with Python 3,
+    if sys.version_info[:2] < (3, 6):
+        # make the pipes compatible with Python >= 3.6,
         # reading lines should output unicode
         encoding = 'utf-8'
         proc_stdout = codecs.getreader(encoding)(proc_stdout)
         proc_stderr = codecs.getreader(encoding)(proc_stderr)
```

And let me know if that works on Ubuntu Xenial.

**Comment by AMS21** [comment]
Thanks for the incredible fast answer. Sadly with the patch I am getting more errors:
> run-clang-format.py: error: OpenEast/include/Platform/Win32/Win32_Registry.hpp: TypeError: can't concat bytes to str
Traceback (most recent call last):
  File "/home/travis/build/AMS21/OpenEast/deps/run-clang-format/run-clang-format.py", line 118, in run_clang_format_diff_wrapper
    ret = run_clang_format_diff(args, file)
  File "/home/travis/build/AMS21/OpenEast/deps/run-clang-format/run-clang-format.py", line 179, in run_clang_format_diff
    outs = list(proc_stdout.readlines())
  File "/usr/lib/python3.5/codecs.py", line 615, in readlines
    data = self.read()
  File "/usr/lib/python3.5/codecs.py", line 497, in read
    data = self.bytebuffer + newdata
TypeError: can't concat bytes to str

**Comment by Sarcasm** [comment]
A quick google search mentionned `codecs.getincrementaldecoder('utf-8')`.

Can you try that:

```patch
-    if sys.version_info[0] < 3:
-        # make the pipes compatible with Python 3,
+    if sys.version_info[:2] < (3, 6):
+        # make the pipes compatible with Python >= 3.6,
         # reading lines should output unicode
         encoding = 'utf-8'
-        proc_stdout = codecs.getreader(encoding)(proc_stdout)
+        proc_stdout = codecs.getincrementaldecoder(encoding)(proc_stdout)
-        proc_stderr = codecs.getreader(encoding)(proc_stderr)
+        proc_stderr = codecs.getincrementaldecoder(encoding)(proc_stderr)
```

**Comment by AMS21** [comment]
Still getting the same error :/

**Comment by Sarcasm** [comment]
It's a pity.
I don't have access to Python 3.5, so it's difficult to debug.
If you don't have access either, I would recommend you to try using python 2, or python >= 3.6, but I understand it's not always possible.

**Comment by AMS21** [comment]
Upgrading to Python 3.6 should be no problem.
Thanks anyways :)

**Comment by Sarcasm** [comment]
I'm closing as I'm not sure sure, but if python 3.5 matters to anyone, feel free to open a PR.
