### ISSUE TITLE
UnicodeDecodeError on files with unicode strings

### ISSUE THREAD

**Issue by Broxzier** [Sarcasm/run-clang-format#5]
Running the script on this source file will error:

```cpp
int main()
{
	auto t = u8"遊";
	return 0;
}
```

Error:
```
run-clang-format.py: error: test.cpp: UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 32: character maps to <undefined>
Traceback (most recent call last):
  File "X:\run-clang-format.py", line 93, in run_clang_format_diff_wrapper
    ret = run_clang_format_diff(args, file)
  File "X:\run-clang-format.py", line 126, in run_clang_format_diff
    outs = list(proc_stdout.readlines())
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 32: character maps to <undefined>
```

Running clang-format on the file works fine.

**Comment by janisozaur** [comment]
For me it works just fine.

```
$ python --version
Python 3.6.5
$ clang-format --version
clang-format version 6.0.0 (tags/RELEASE_600/final)
$ uname -a
Linux trurl 4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018 x86_64 GNU/Linux
$ xxd -i test.cpp 
unsigned char test_cpp[] = {
  0x69, 0x6e, 0x74, 0x20, 0x6d, 0x61, 0x69, 0x6e, 0x28, 0x29, 0x0a, 0x7b,
  0x0a, 0x09, 0x61, 0x75, 0x74, 0x6f, 0x20, 0x74, 0x20, 0x3d, 0x20, 0x75,
  0x38, 0x22, 0xe9, 0x81, 0x8a, 0x22, 0x3b, 0x0a, 0x09, 0x72, 0x65, 0x74,
  0x75, 0x72, 0x6e, 0x20, 0x30, 0x3b, 0x0a, 0x7d, 0x0a
};
unsigned int test_cpp_len = 45;
$ ./run-clang-format.py test.cpp 
--- test.cpp	(original)
+++ test.cpp	(reformatted)
@@ -1,5 +1,4 @@
-int main()
-{
-	auto t = u8"遊";
-	return 0;
+int main() {
+  auto t = u8"遊";
+  return 0;
 }
```

**Comment by Broxzier** [comment]
I'm on the exact same versions of python and clang-format, only on Windows 10 instead.

```
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64>python.exe --version
Python 3.6.5
C:\Program Files\LLVM\bin>clang-format.exe --version
clang-format version 6.0.0 (tags/RELEASE_600/final)
```

**Comment by Broxzier** [comment]
This may be related, though here it doesn't fail. This is output on another file with a special character:

```diff
-        // Render capital sharp-S (ẞ) with lowercase sprite (ß)
+        // Render capital sharp-S (áºž) with lowercase sprite (ÃŸ)
```

**Comment by Sarcasm** [comment]
If you are in Python 3, I tried to let Python do its Unicode things naturally.
The error you get, seems to be from this line:

https://github.com/Sarcasm/run-clang-format/blob/0450a3f7848e5adb9706145c4eea8116631756a5/run-clang-format.py#L126

I open the subprocess pipe with `universal_newlines` enabled:

https://github.com/Sarcasm/run-clang-format/blob/0450a3f7848e5adb9706145c4eea8116631756a5/run-clang-format.py#L110-L114

The Python 3.6 documentation says:

> If encoding or errors are specified, or universal_newlines is true, file objects for stdin, stdout and stderr are opened in text mode using the specified encoding and errors or the io.TextIOWrapper default. > Otherwise, file objects are opened in binary mode.
> -- https://docs.python.org/3/library/subprocess.html#using-the-subprocess-module

As `universal_newlines` is enabled, the `io.TextIOWrapper` default should be used:

> encoding gives the name of the encoding that the stream will be decoded or encoded with.
> It defaults to locale.getpreferredencoding(False).
> -- https://docs.python.org/3/library/io.html#io.TextIOWrapper


So, I can imagine a few fixes:

- check if your system local is correctly configured, try to set another local for testing (don't ask me how to do that, I have no idea on Windows)
- force encoding to 'utf-8', I invite you to try that by adding `encoding='utf-8` to the `subprocess.Popen()` call

When I read files, I read them in 'utf-8', which I think is a sane value for C++, I don't want to deal with anything else.

For standard input/output streams and for process output streams, I don't force the encoding, and let Python 3 do its thing.

**Comment by Broxzier** [comment]
Thanks, setting the encoding argument in `subprocess.Popen` seems to work around this problem. I can now run it on my Windows machine without encoding errors. I was curious why I got them though:

```
>>> import locale;
>>> locale.getpreferredencoding();
'cp1252'
>>> f = open('test.cpp');
>>> f.encoding
'cp1252'
```

It looks like it indeed defaults to the machine's locale, which is CP-1252 on Windows by default. Even saving the source file with the UTF-8 BOM doesn't work around this issue.

If you only want to support utf-8 files anyway, I assume it wouldn't hurt to add the encoding argument to the script by default, and make it easier for Windows users.

**Comment by Sarcasm** [comment]
Ok, I guess it may be a good idea to force the 'utf-8' encoding.

Assuming these two things are true (which I'm not sure):
- Clang doesn't care about the input file encoding, and will output "bytes" read from the file, in which case we should use the same encoding that we use when reading the file ourselves (utf-8)
- Clang diagnostics are utf-8 even in case of translation:

   > Adding Translations to Clang
   >
   > Not possible yet! **Diagnostic strings should be written in UTF-8**, the client can translate to the relevant code page if needed. Each translation completely replaces the format string for the diagnostic.
   > -- http://clang.llvm.org/docs/InternalsManual.html#internals-diag-translation

**Comment by Sarcasm** [comment]
Should be fixed by https://github.com/Sarcasm/run-clang-format/commit/5e5902e744d8c55ebd5173f07a4ee3a336e17e03

Feel free to reopen if it's not working.

**Comment by Broxzier** [comment]
Can confirm that it's fixed :+1:
